services:
  - type: web
    name: erpnext-qsr-web
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        value: erpnext-db-holy-ember.sage.cloud.layerbase.dev
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        value: avnadmin
      - key: DB_PASSWORD
        value: Eg4Tjjoe5BtvsD7T1VcIBHXF
      - key: ADMIN_PASSWORD
        value: YourSecureAdminPassword123
      - key: REDIS_CACHE
        value: mysql://root:Eg4Tjjoe5BtvsD7T1VcIBHXF@erpnext-db-holy-ember.ovh2.cloud.layerbase.dev:22091/erpnext_db?ssl-mode=REQUIRED

  - type: worker
    name: erpnext-qsr-worker
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerCommand: bench worker --queue default,short,long
