services:
  # 1. Main ERPNext Web Application
  - type: web
    name: qsr-erpnext-web
    env: dockerfile
    plan: starter # Render Starter Tier
    dockerfilePath: ./Dockerfile
    dockerCommand: bench serve --port 8000
    envVars:
  
 
