services:
  # 1. Main ERPNext Web Application
  - type: web
    name: qsr-erpnext-web
    env: docker
    plan: starter # Render Starter Tier
    dockerfilePath: ./Dockerfile
    dockerCommand: bench serve --port 8000
    envVars:
      - key: DB_HOST
        value: "erpnext-db-holy-ember.sage.cloud.layerbase.dev" # Replace with your Layerbase Host
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        value: "erpnext_db"
      - key: MARIADB_ROOT_PASSWORD
        value: "Eg4Tjjoe5BtvsD7T1VcIBHXF" # Replace with your Layerbase Password

  # 2. ERPNext Background Worker (Handles background queues & POS sync)
  - type: worker
    name: qsr-erpnext-worker
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerCommand: bench worker --queue default,short,long
    envVars:
      - key: DB_HOST
        value: "YOUR_LAYERBASE_HOST"
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        value: "erpnext_db"
